name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      PORT: 80
      DEPLOYMENT_NAME: app-example-deployment
      NAMESPACE: app-example

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      id: build-image
      run: |
        IMAGE_TAG=${{ secrets.DOCKER_USERNAME }}/my-image-name:$(date +%s)
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
        docker build . --file Dockerfile --tag $IMAGE_TAG

    - name: Push the Docker image
      run: docker push ${{ env.IMAGE_TAG }}

    - name: Checkout the target repository
      uses: actions/checkout@v4
      with:
        repository: mohamadalsalty/github-actions-cd
        token: ${{ secrets.TARGET_REPO_PAT }}
        path: cd-repo

    - name: Copy YAML files to target repository
      run: |
        cp deployment.yaml cd-repo/

    - name: Modify placeholders in YAML files with sed
      run: |
        sed -i 's|IMAGE_NAME_WITH_TAG|${{ env.IMAGE_TAG }}|g' cd-repo/deployment.yaml
        sed -i 's|PORT|${{ env.PORT }}|g' cd-repo/deployment.yaml
        sed -i 's|DEPLOYMENT_NAME|${{ env.DEPLOYMENT_NAME }}|g' cd-repo/deployment.yaml
        sed -i 's|NAMESPACE|${{ env.NAMESPACE }}|g' cd-repo/deployment.yaml

    - name: Commit and push changes
      run: |
        cd cd-repo
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Update deployment files with new image tag, port, deployment name, and namespace"
        git push origin main

    - name: Print the image tag
      run: echo "Docker image tag is ${{ env.IMAGE_TAG }}"
